# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_plugins {
    virtualbox = {
      source  = "github.com/hashicorp/virtualbox"
      version = "~> 1"
    }
    vagrant = {
        source = "github.com/hashicorp/vagrant"
        version = ">= 1.1.1"
    }
  }
}

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "iso_checksum" {
  type    = string
  default = "dec49008a71f6098d0bcfc822021f4d042d5f2db279e4d75bdd981304f1ca5d9"
}

variable "iso_checksum_type" {
  type    = string
  default = "sha256"
}

variable "iso_url" {
  type    = string
  default = "https://releases.ubuntu.com/resolute/ubuntu-26.04-live-server-amd64.iso"
}


# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "virtualbox-iso" "ubuntu2604" {
  boot_command = [
    "c<wait>",
    "linux /casper/vmlinuz boot=casper autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/' ---<enter>",
    "initrd /casper/initrd<enter>",
    "boot<enter>"
  ]
  boot_wait         = "5s"
  disk_size         = 20240
  guest_os_type     = "Ubuntu_64"
  headless          = true
  http_directory    = "http"
  iso_checksum      = "${var.iso_checksum_type}:${var.iso_checksum}"
  iso_url           = "${var.iso_url}"
  shutdown_command  = "echo 'ubuntu' | sudo -S shutdown -P now"
  ssh_username      = "vagrant"
  ssh_password      = "vagrant"
  ssh_timeout       = "20m"
  ssh_wait_timeout  = "30m"
  vm_name           = "ubuntu-26.04-vm"


  vboxmanage = [
    ["modifyvm", "{{.Name}}", "--memory", "10240"],
    ["modifyvm", "{{.Name}}", "--cpus", "6"]
  ]
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.virtualbox-iso.ubuntu2604"]

  provisioner "shell" {
    inline = [
        "echo 'Installing dependencies for Guest Additions...'",
        "sudo apt-get update -y",
        "sudo apt-get install -y build-essential dkms linux-headers-$(uname -r)",
        "echo 'Dependencies installed.'"
      ]
  }

  provisioner "shell" {
    inline = [
        "sudo apt-get install -y virtualbox-guest-additions-iso"
    ]
  }

  provisioner "shell" {
      inline = [
        "echo 'Mounting Guest Additions ISO...'",
        "sudo mount /usr/share/virtualbox/VBoxGuestAdditions.iso /mnt || echo 'Failed to mount ISO.'",
        "cd /mnt",
        "sudo sh /mnt/VBoxLinuxAdditions.run || echo 'Installation returned a non-zero exit code'",
        "sudo umount -l /mnt || echo 'Error unmounting'",
      ]
      pause_before = "10s"
  }

  provisioner "shell" {
    inline = [
      "echo 'Enabling colored prompt and tools for vagrant user...'",
      "sudo -u vagrant -H bash -c \"sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' ~/.bashrc\"",
      "sudo -u vagrant -H bash -c \"grep -q '^export TERM=xterm-256color$' ~/.bashrc || echo 'export TERM=xterm-256color' >> ~/.bashrc\"",
      "sudo -u vagrant -H bash -c \"if [ ! -f ~/.bash_profile ] || ! grep -q '\\\\. ~/.bashrc' ~/.bash_profile; then echo 'if [ -f ~/.bashrc ]; then . ~/.bashrc; fi' >> ~/.bash_profile; fi\"",
      "echo 'Color configuration applied.'"
    ]
  }

  provisioner "shell" {
    inline = [
      "echo 'Cleaning up...'",
      "sudo apt-get clean",
      "sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*",
      "echo 'Clean-up complete!'"
    ]
  }


  post-processor "vagrant" {
    output = "ubuntu-26.04.box"
  }

}